"""Shared synthetic kwargs for BudgetConditionedAdaptiveF2FNet CPU checks."""

from __future__ import annotations


def synthetic_budget_f2f_kwargs(
    node_size: int = 7,
    input_len: int = 12,
    output_len: int = 12,
    inference_intensity: float = 0.5,
    forced_route=None,
    route_selection_mode: str = "batch",
    loss_mode: str = "baseline_compatible",
    training_phase: str = "eval",
) -> dict:
    return {
        "node_size": node_size,
        "input_len": input_len,
        "output_len": output_len,
        "input_dim": 4,
        "output_dim": 1,
        "patch_len": 3,
        "stride": 4,
        "td_size": 288,
        "dw_size": 7,
        "d_td": 16,
        "d_dw": 16,
        "d_d": 16,
        "d_spa": 16,
        "num_layer": 1,
        "if_time_in_day": True,
        "if_day_in_week": True,
        "if_spatial": True,
        "spatial_scheme": "C",
        "use_patch_branch": True,
        "use_downsample_branch": True,
        "use_linear_residual_branch": True,
        "patch_embedding_mode": "serial_concat",
        "patch_data_input_mode": "all",
        "use_prev_condition": True,
        "spatial_placement": "interleaved_progressive",
        "progressive_spatial_ratios": [0.25, 0.5, 1.0],
        "progressive_spatial_topks": [4, 8, 16],
        "progressive_spatial_alphas": [0.03, 0.06, 0.10],
        "post_spatial_mode": "adaptive_only",
        "use_adaptive_adj": True,
        "use_dynamic_spatial": False,
        "use_gcn": False,
        "adp_hidden_dim": 16,
        "use_forecast_state_adapter": True,
        "forecast_state_adapter_mode": "condition_only",
        "forecast_state_adapter_hidden_dim": 16,
        "forecast_state_adapter_epsilon": 0.02,
        "inference_intensity": inference_intensity,
        "route_selection_mode": route_selection_mode,
        "route_granularity": "batch",
        "route_cost_type": "normalized_static_cost",
        "planner_hidden_dim": 32,
        "training_phase": training_phase,
        "loss_mode": loss_mode,
        "forced_route": forced_route,
        "dataset_name": "synth_budget_f2f",
    }
